services:
  - type: web
    name: elmis-eswatini-frontend
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/YOUR_USERNAME/my-app.git
    branch: main
    rootDir: eswatini_lmis_frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: REACT_APP_API_URL
        value: https://elmiseswatini-backend.onrender.com
      - key: REACT_APP_API_BASE
        value: https://elmiseswatini-backend.onrender.com
      - key: REACT_APP_FRONTEND_URL
        value: https://elmis-eswatini-qzwo.onrender.com
      - key: NODE_ENV
        value: production

  - type: web
    name: lmis-backend
    runtime: docker
    plan: free
    region: oregon
    repo: https://github.com/YOUR_USERNAME/my-app.git
    dockerfilePath: ./eswatini_lmis_backend/Dockerfile
    branch: main
    envVars:
      - key: PORT
        value: 3001
      - key: DB_HOST
        value: dpg-d8fb0ca8qa3s738qh880-a.oregon-postgres.render.com
      - key: DB_USER
        value: eswatini_lmis_user
      - key: DB_NAME
        value: eswatini_lmis
      - key: DB_PORT
        value: 5432
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
